### ISSUE TITLE
Boas

### ISSUE THREAD

**Issue by moodyblue** [dgomes/pyprosegur#1]
Viva, para que é que isto serve ? Como se usa ? Tenho instalado um alarme prosegur e estou à procura de uma forma de saber qual o estado do alarme para o poder usar num sistema de automação.

**Comment by dgomes** [comment]
Para por exemplo utilizar num sistema de automação :)

https://github.com/dgomes/ha_prosegur

**Comment by moodyblue** [comment]
Suspeitei... Mas a minha onda é Openhab

**Comment by dgomes** [comment]
Claro, é só reutilizar o código que já aqui está, tens o componente HA como exemplo de utilização

**Comment by moodyblue** [comment]
Lá vou eu ter de estudar isto... Aprendi Fortran faz 50 anos, há coisas que nunca esquecem... E curiosamente habito em Aveiro, vi no CPHA que és de cá

**Comment by moodyblue** [comment]
Pergunta parva, isto é Python 2 ou 3 ?

**Comment by dgomes** [comment]
Python3

existe um ficheiro cli.py que pode ser usado para as operações todas via linha de comandos ;)

Como isto não é verdadeiramente uma issue, vou fechar

**Comment by moodyblue** [comment]
Obrigado
